#!/bin/bash

# Utility script to create the README.pdf file from the README file, in a
# consistent fashion as we occasionally need to update the README file.

\enscript -p - -fCourier8 --margins=20:20:18:18 README > README.ps
ps2pdf README.ps
rm README.ps
