insert into jbp_users (jbp_uid, jbp_uname, jbp_password, jbp_realemail, jbp_regdate, jbp_viewrealemail, jbp_enabled) values ('1', 'admin', MD5('admin'), 'portal@example.com', NOW(), '1', '1');  
insert into jbp_users (jbp_uid, jbp_uname, jbp_password, jbp_realemail, jbp_regdate, jbp_viewrealemail, jbp_enabled) values ('2', 'user', MD5('user'), 'portal@example.com', NOW(), '1', '1');  
insert into jbp_users (jbp_uid, jbp_uname,jbp_givenname,jbp_familyname,jbp_password, jbp_realemail, jbp_regdate, jbp_viewrealemail, jbp_enabled) values ('4', 'wsuser','System Account','DO NOT disable/delete this user! If you change the password, don''t forget to update the /usr/local/groundwork/config/ws_client.properties file!', MD5('wsuser'), 'portal@example.com', NOW(), '1', '1');  
insert into jbp_roles (jbp_rid, jbp_name, jbp_displayname) values ('1', 'GWAdmin', 'Administrators');
insert into jbp_roles (jbp_rid, jbp_name, jbp_displayname) values ('2', 'GWUser', 'Users');
insert into jbp_roles (jbp_rid, jbp_name, jbp_displayname) values ('6', 'wsuser', 'Webservice users');
insert into jbp_role_membership (jbp_uid, jbp_rid) values ('1', '1');
insert into jbp_role_membership (jbp_uid, jbp_rid) values ('2', '2');
insert into jbp_role_membership (jbp_uid, jbp_rid) values ('4', '6');
INSERT INTO gw_entitytype(entitytype_id, entitytype) VALUES (1, 'HostGroup');
INSERT INTO gw_entitytype(entitytype_id, entitytype) VALUES (2, 'ServiceGroup');
INSERT INTO gw_entitytype(entitytype_id, entitytype) VALUES (3, 'CustomGroup');
