#!/bin/sh
# $Id: $
#
# Copyright 2009-2013 GroundWork Open Source, Inc. ("GroundWork")
# All rights reserved. This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
# Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# Script for Supervise : Jetty container

export GW_HOME=/usr/local/groundwork
cd $GW_HOME/foundation/container/jpp/bin

FoundationPID=`ps -ef | grep -v grep | grep jpp | grep standalone | awk '{print $2}'`
if ! [ -z "$JbossPID" ] ; then
        echo "Foundation Services Already Running"
        echo "    FoundationPID: $FoundationPID"
        exit 1
fi

# GWMON-10930:  Before we start, clean up any mess left over from previous
# portal invocations, to avoid a persistent filesystem-space leak.
/bin/rm -rf /usr/local/groundwork/foundation/container/jpp/standalone/tmp/

exec $GW_HOME/common/bin/setuidgid nagios ./standalone.sh
