################################################################################
#
#   gdma_auto.conf
#
#   Copyright 2010 Groundwork Open Source, Inc.
#   http://www.groundworkopensource.com
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, 
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and 
#   limitations under the License.
#
################################################################################

# Note:  This gdma_auto.conf file is essentially just a dummy file
# to satisfy the GDMA spooler initialization.  It will be read, and
# therefore must be present, but it will not actually be used to pull
# new gwmon_{yourhost}.cfg files from anywhere.  Don't alter anything
# in this file.

# Parameters which are useful to the GDMA spooler.
#
Enable_Auto = "off"
Enable_Local_Logging = "off"
Logdir = "/usr/local/groundwork/gdma/log/"
Spooler_Batch_Size = "200"
Spooler_Max_Retries = "10"
Spooler_NSCA_Config = "/usr/local/groundwork/common/etc/send_nsca.cfg"
Spooler_NSCA_Port = "5667"
Spooler_NSCA_Program = "/usr/local/groundwork/common/bin/send_nsca"
Spooler_NSCA_Timeout = "30"
Spooler_Proc_Interval = "30"
Spooler_Retention_Time = "900"
Spooler_Service = "gdma_spooler"
Spooler_Status = "off"
# Target_Server = "http://gdma-autohost"

# Parameters which would be useful to the GDMA poller,
# which we are not running in this child-server context.
#
# ConfigFile_Pull_Cycle = "1"
# ConfigPull_Timeout = "10"
# GDMAConfigDir = "gdma"
# GDMA_Auto_Host = "gdma-autohost"
# GDMA_Auto_Service = "gdma_auto"
# GDMA_Multihost = "off"
# Host_Name_Prefix= "foo-"
# Max_Concurrent_Hosts = "1"
# Poller_Plugin_Directory = "/usr/local/groundwork/nagios/libexec"
# Poller_Plugin_Timeout = "5"
# Poller_Proc_Interval = "600"
# Poller_Pull_Failure_Interval = "86400"
# Poller_Service = "gdma_poller"
