#!/bin/sh
# Script for Supervise : Nagios fping Feeder
exec /usr/local/groundwork/common/bin/setuidgid nagios /usr/local/groundwork/foundation/feeder/fping_process.pl >> /dev/null
#/usr/local/groundwork/common/var/log/fping_feeder.log
