# makefile for the archive gwservices control program

# Copyright (c) 2013 GroundWork, Inc. (www.gwos.com).  All rights reserved.
# Use is subject to GroundWork commercial license terms.

control_archive_gwservices	: control_archive_gwservices.c
	cc -o $@ control_archive_gwservices.c

clean	:
	rm -f control_archive_gwservices

distclean	: clean
