#!/bin/sh
# Script for Supervise : GDMA Spooler

# Sleep for 30 seconds before startup.  This helps prevent a tight loop
# if the startup should fail repeatedly, say because the configuration
# file is not yet set up for localized operation.
sleep 30

exec /usr/local/groundwork/common/bin/setuidgid nagios /usr/local/groundwork/perl/bin/perl /usr/local/groundwork/gdma/bin/gdma_spool_processor.pl >> /dev/null
