#!/bin/bash -e

# dump_cacti_realtime_plugin_table
#
# Script to dump out the new table object used by the Cacti "realtime" plugin,
# to create the realtime_table_for_migration_to_postgresql.sql.tar.gz file.  See
# the README in this directory for more information about this tarball and how it
# is to be used to migrate from a MySQL-based Cacti release to a PostgreSQL-based
# Cacti release.
#
# Copyright (c) 2016 GroundWork, Inc.  All rights reserved.

# Here is the object of interest:
#
# cacti=# \dts poller_output_rt
#                List of relations
#  Schema |       Name       | Type  |   Owner   
# --------+------------------+-------+-----------
#  public | poller_output_rt | table | cactiuser
# (1 row)

dbhost=localhost
dbname=cacti
dbuser=postgres
sqlfile=realtime_table_for_migration_to_postgresql.sql

echo ""
echo "You wiil be asked for the \"$dbuser\" user's PostgreSQL password,"
echo "to dump the schema for the desired object from the database."
echo ""

# Logically, we would like to use the "--if-exists" option here as well.  But the SQL we
# generate might get used on a PostgreSQL 9.1.X system, wherein PostgreSQL does not yet
# support the "ALTER TABLE IF EXISTS" syntax that would generate.  So we must forgo that
# part of the dump, and simply tolerate the errors that will result.
#
/usr/local/groundwork/postgresql/bin/pg_dump "--host=$dbhost" "--username=$dbuser" \
    "--file=$sqlfile" --format=plain --clean --schema-only --encoding=LATIN1 \
    -t 'public.poller_output_rt' \
    $dbname

if tar cfz $sqlfile.tar.gz $sqlfile; then
    rm -f $sqlfile
    echo ""
    echo "The desired tarball is now available:"
    echo ""
    echo "    $sqlfile.tar.gz"
    echo ""
fi
