#!/usr/local/groundwork/perl/bin/perl -w --

# Program to convert a eucarc script (part of the standard Eucalyptus
# credentials), which is only suitable for use with bash, to an
# equivalent script which is suitable for use with tcsh.  The primary
# difference is that we fix the location of the EUCA_KEY_DIR, making
# the assumption that it will be the same directory as the eucarc
# file is currently found in rather than dynamically setting it at
# the time our output file is sourced.

# Copyright 2010 GroundWork Open Source, Inc. ("GroundWork").  All rights
# reserved.  Use is subject to GroundWork commercial license terms.

use Cwd 'realpath';
use File::Basename;

if (scalar @ARGV != 1) {
    print "usage:  convert_eucarc_for_tcsh eucarc > access.tcsh\n";
    print "then later in tcsh:\n";
    print "        source access.tcsh\n";
    exit 1;
}

my $file_path = ($ARGV[0] =~ m{^/}) ? $ARGV[0] : "$ENV{PWD}/$ARGV[0]";
my $file_dir = dirname realpath $file_path;
    
while (<>) {
    if (/^\s*#/) {
	print;
    }
    elsif (/^export ([^=]+)=(.+)/) {
	print "setenv $1 $2\n";
    }
    elsif (/^alias ([^=]+)=(.+)/) {
	print "alias $1 $2\n";
    }
    elsif (/^EUCA_KEY_DIR=/) {
	print "set EUCA_KEY_DIR = $file_dir\n";
    }
    else {
	print "# Unknown input line:\n";
	print "# $_";
    }
}
