-- Copyright (C) 2004-2009  GroundWork Open Source Solutions info@groundworkopensource.com
--
--    This program is free software; you can redistribute it and/or modify
--    it under the terms of version 2 of the GNU General Public License
--    as published by the Free Software Foundation and reprinted below;
--
--    This program is distributed in the hope that it will be useful,
--    but WITHOUT ANY WARRANTY; without even the implied warranty of
--    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--    GNU General Public License for more details.
--
--    You should have received a copy of the GNU General Public License
--    along with this program; if not, write to the Free Software
--    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
--
-- 
--------------------------------------
-- Add default hostgroup to Foundation
----------------------------------------
INSERT INTO MonitorServer (MonitorServerName,IP,Description) VALUES('localhost','127.0.0.1','Default Monitor Server');
INSERT INTO HostGroup (Name, Description, ApplicationTypeID) VALUES ('Linux Servers', 'HostGroup for all Linux Servers', (SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'));
INSERT INTO Device (DisplayName, Identification, Description) VALUES('127.0.0.1','127.0.0.1','Device localhost');
INSERT INTO MonitorList (MonitorServerID,DeviceID) VALUES((Select MonitorServerID from MonitorServer where MonitorServerName='localhost'),(Select DeviceID from Device where Identification='127.0.0.1'));
INSERT INTO Host (DeviceID, HostName, Description, ApplicationTypeID) VALUES((SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),'localhost','Host localhost',(SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'));
INSERT INTO HostStatus (HostStatusID, ApplicationTypeID,MonitorStatusID,LastCheckTime,CheckTypeID) VALUES((SELECT HostID from Host Where HostName='localhost'), (SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), (SELECT MonitorStatusID from MonitorStatus WHERE Name='PENDING'), NOW(), (SELECT CHeckTypeID from CheckType WHERE Name='ACTIVE'));
INSERT INTO HostGroupCollection(HostID, HostGroupID) VALUES ((SELECT HostID FROM Host WHERE HostName='localhost'),(SELECT HostGroupID FROM HostGroup WHERE Name='Linux Servers'));

-- Add HostStatus to initial load

--INSERT INTO HostStatus(HostStatusID, ApplicationTypeID, MonitorStatusID, LastCheckTime) VALUES( (SELECT HostID FROM Host WHERE HostName='localhost'),(SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), (SELECT MonitorStatusID FROM MonitorStatus WHERE NAME='PENDING' ), NOW()); 

-- Add Service Status to out of the box services

INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_cpu_httpd',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_cpu_java',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_cpu_nagios',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_cpu_perl',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_cpu_syslog-ng',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_users',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_disk_root',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_load',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_memory',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_mem_httpd',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_mem_java',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_mem_nagios',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_mem_perl',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_mem_syslog-ng',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_nagios_latency',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_process_gw_listener',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_process_nagios',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'local_swap',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'tcp_gw_listener',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'tcp_http',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());
INSERT INTO ServiceStatus(ApplicationTypeID, ServiceDescription, MonitorStatusID, StateTypeID, CheckTypeID, LastHardStateID, HostID, LastStateChange, NextCheckTime, LastCheckTime)
VALUES((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'), 'tcp_nsca',(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'), (SELECT StateTypeID FROM StateType WHERE Name='HARD'),(SELECT CheckTypeID FROM CheckType WHERE Name='ACTIVE'),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT HostID FROM Host WHERE HostName='localhost'), NOW(), NOW(), NOW());


INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),null,'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);

INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_cpu_httpd'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_cpu_java'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_cpu_nagios'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_cpu_perl'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_cpu_syslog-ng'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_users'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_disk_root'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_load'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_memory'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_mem_httpd'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_mem_java'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_mem_nagios'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_mem_perl'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_mem_syslog-ng'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_nagios_latency'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_process_gw_listener'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_process_nagios'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='local_swap'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='tcp_gw_listener'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='tcp_http'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
INSERT INTO LogMessage  (applicationtypeid, deviceid, hoststatusid, servicestatusid, textmessage, msgcount, firstinsertdate, lastinsertdate, reportdate,monitorstatusid,severityid,applicationseverityid ,priorityid,typeruleid,componentid,operationstatusid,isstatechanged,consolidationhash,statelesshash,statetransitionhash)
values ((SELECT ApplicationTypeID FROM ApplicationType WHERE Name='NAGIOS'),(SELECT DeviceID FROM Device WHERE Identification='127.0.0.1'),(SELECT hostid from Host where hostname='localhost'),(select servicestatusid from servicestatus where servicedescription='tcp_nsca'),'PENDING',1,NOW(),NOW(),NOW(),(SELECT MonitorStatusID FROM MonitorStatus WHERE Name='PENDING'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),(SELECT SeverityID FROM Severity WHERE Name='LOW'),1,(select typeruleid from typerule where name='UNDEFINED'),(select componentid from component where name='UNDEFINED'),(select operationstatusid from operationstatus where name='ACCEPTED'),'f',0,0,null);
