--
-- Table structure for table JMS_MESSAGES
--
DROP TABLE IF EXISTS HILOSEQUENCES;
DROP TABLE IF EXISTS JMS_MESSAGES;
DROP TABLE IF EXISTS JMS_ROLES;
DROP TABLE IF EXISTS JMS_SUBSCRIPTIONS;
DROP TABLE IF EXISTS JMS_TRANSACTIONS;
DROP TABLE IF EXISTS JMS_USERS;
DROP TABLE IF EXISTS TIMERS;