#!/bin/sh

# probe for system attributes

# Redirect errors into the standard output stream.
exec 2>&1

echo
echo "uname -a:"
uname -a

echo
echo "uname -s:"
uname -s

echo
echo "uname -n:"
uname -n

echo
echo "uname -r:"
uname -r

echo
echo "uname -v:"
uname -v

echo
echo "uname -m:"
uname -m

echo
echo "uname -p:"
uname -p

echo
echo "uname -i:"
uname -i

echo
echo "uname -o:"
uname -o

echo
echo "uname -l:"
uname -l

echo
echo "model:"
model

echo
echo "getconf:"
getconf

echo
echo "getconf KERNEL_BITS:"
getconf KERNEL_BITS

echo
echo "getconf SC_KERNEL_BITS:"
getconf SC_KERNEL_BITS

echo
echo "getconf _SC_KERNEL_BITS:"
getconf _SC_KERNEL_BITS

echo
echo "getconf CS_KERNEL_BITS:"
getconf CS_KERNEL_BITS

echo
echo "getconf _CS_KERNEL_BITS:"
getconf _CS_KERNEL_BITS

echo
echo "getconf CPU_CHIP_TYPE:"
getconf CPU_CHIP_TYPE

echo
echo "getconf CPU_KEYBITS1:"
getconf CPU_KEYBITS1

echo
echo "getconf CPU_VERSION:"
getconf CPU_VERSION

echo
echo "getconf HW_CPU_SUPP_BITS:"
getconf HW_CPU_SUPP_BITS

echo
echo "getconf CS_HW_CPU_SUPP_BITS:"
getconf CS_HW_CPU_SUPP_BITS

echo
echo "getconf _CS_HW_CPU_SUPP_BITS:"
getconf _CS_HW_CPU_SUPP_BITS

echo
echo "getconf HW_32_64_CAPABLE:"
getconf HW_32_64_CAPABLE

echo
echo "getconf MACHINE_MODEL:"
getconf MACHINE_MODEL

echo
echo "getconf CS_MACHINE_MODEL:"
getconf CS_MACHINE_MODEL

echo
echo "getconf _CS_MACHINE_MODEL:"
getconf _CS_MACHINE_MODEL

echo
echo "getconf POSIX_PIPE_BUF:"
getconf POSIX_PIPE_BUF

echo
echo "getconf -a:"
getconf -a

echo
echo "ps -e -x:"
ps -e -x

