#!/bin/bash -e

# This is the pre_build_hook script for the fuel-plugin-groundwork-monitor RPM.

#
# Copyright 2016-2017 GroundWork Open Source, Inc. (GroundWork)
# All rights reserved. This program is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#

# Add here any actions which are required before plugin build like
# package building, packages downloading from mirrors and so on.
# The script should return 0 if there were no errors.

# In point of fact, for the present plugin, all such actions that we
# actually wish to run have been centralized within the Makefile, so
# there is just one place that certain configuration data must be
# maintained across releases.

exit 0
