#!/bin/sh
# Script for Supervise : Nagios fping Feeder

# Sleep for 20 seconds before startup.  This helps prevent a tight loop
# if the startup should fail repeatedly.
sleep 20

exec /usr/local/groundwork/common/bin/setuidgid nagios /usr/local/groundwork/foundation/feeder/fping_process.pl >> /dev/null
#/usr/local/groundwork/common/var/log/fping_feeder.log
