#!/bin/sh
# Apache control script
#
#
# Copyright 2007 GroundWork Open Source, Inc. ("GroundWork")  
# All rights reserved. This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51 Franklin # Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
### BEGIN INIT INFO
# Provides: httpd
# Required-Start: $local_fs $remote_fs
# X-UnitedLinux-Should-Start: $named $syslog $time
# Required-Stop:  $local_fs $remote_fs
# X-UnitedLinux-Should-Stop: $named $syslog $time
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: Apache web server
# Description: Apache HTTP Server Version 2.0
### END INIT INFO

export GW_HOME=/usr/local/groundwork
export PATH=$GW_HOME/bin:$GW_HOME/sbin:$PATH
status_httpd ()
{
	httpd_PID=( `ps -ef |grep -v grep|grep "httpd"|awk '{print $2}'` )

        if ! [ -z "${httpd_PID[0]}" ] ; then
        	if ! [ -z "${httpd_PID[1]}" ] ; then
        		if ! [ -z "${httpd_PID[2]}" ] ; then
        			if ! [ -z "${httpd_PID[3]}" ] ; then
        				if ! [ -z "${httpd_PID[4]}" ] ; then
        					if ! [ -z "${httpd_PID[5]}" ] ; then
							return 0
						fi
					fi
				fi
			fi
		fi
	fi	
return 1
}


        case "$1" in
           	start)
                # Check status
                status_httpd httpd
                echo  -n "Starting Groundwork Apache Server"
		$GW_HOME/apache2/bin/apachectl start > /dev/null

		if [ $? -eq 0  ] ; then
                	echo -en '\E[0m'"\033[61G[\033[0m"
                	echo -e '\E[1;37;32m'"\033[63GOK\033[0m" ]
                else
                	echo -en '\E[0m'"\033[61G[\033[0m"
                	echo -e '\E[1;37;31m'"\033[63GFAILED\033[0m" ]
                fi
                ;;
          	status)
		status_httpd httpd
                if [ $? -eq 0  ] ; then
                        echo -en '\E[0m'"\033[61G[\033[0m"
                        echo -e  '\E[1;37;32m'"\033[63Grunning\033[0m" ]
                else
                        echo -en '\E[0m'"\033[61G[\033[0m"
                        echo -e  '\E[1;37;31m'"\033[63Gdead\033[0m" ]
                fi
                ;;
            	stop)
                echo -n "Stopping Groundwork Apache Server"
		$GW_HOME/apache2/bin/apachectl stop > /dev/null
                if [ $? -eq 0 ] ; then
                        echo -en '\E[0m'"\033[61G[\033[0m"
                        echo -e '\E[1;37;32m'"\033[63GOK\033[0m" ]
                else
                        echo -en '\E[0m'"\033[61G[\033[0m"
                        echo -e '\E[1;37;31m'"\033[63GFAILED\033[0m" ]
                fi
                ;;
         	restart)
                $0 stop
                $0 start
                ;;
                *)
                echo "Usage:httpd {start|stop|restart|status}"
                exit 1
                ;;
        esac

